version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: contenedor_movieSpringApp_db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - movie-network

  backend:
    build: 
      context: ./movie-spring-app
    container_name: movie-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      - db
    networks:
      - movie-network

  frontend:
    build: 
      context: ./movie-react-app
    container_name: movie-frontend
    ports:
      - "5173:80" 
    depends_on:
      - backend
    networks:
      - movie-network

networks:
  movie-network:
    driver: bridge

volumes:
  postgres_data: